language : java

addons:
  sonarcloud:
    organization: "tardy-lasserve-github"
script:
  # the following command line builds the project, runs the tests with coverage
  # and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=tardy-lasserve_ipi-java-350-ex